// This file is auto-generated by @hey-api/openapi-ts

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    content: string;
    role: 'user' | 'assistant';
    id?: string;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type ChatMessagesPostData = {
    body: Message;
    path?: never;
    query?: never;
    url: '/messages/';
};

export type ChatMessagesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatMessagesPostError = ChatMessagesPostErrors[keyof ChatMessagesPostErrors];

export type ChatMessagesPostResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ChatMessagesPostResponse = ChatMessagesPostResponses[keyof ChatMessagesPostResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: `${string}://apps` | (string & {});
};