// This file is auto-generated by @hey-api/openapi-ts

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    content: string;
    role: 'user' | 'assistant';
    id?: string;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type ChatApiV1ChatPostData = {
    body: Message;
    path?: never;
    query?: never;
    url: '/api/v1/chat/';
};

export type ChatApiV1ChatPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatApiV1ChatPostError = ChatApiV1ChatPostErrors[keyof ChatApiV1ChatPostErrors];

export type ChatApiV1ChatPostResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ChatApiV1ChatPostResponse = ChatApiV1ChatPostResponses[keyof ChatApiV1ChatPostResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckApiV1HealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type HealthCheckApiV1HealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: `${string}://apps` | (string & {});
};