// This file is auto-generated by @hey-api/openapi-ts

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    content: string;
    role: 'user' | 'assistant';
    id?: string;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type ChatApiChatPostData = {
    body: Message;
    path?: never;
    query?: never;
    url: '/api/chat/';
};

export type ChatApiChatPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatApiChatPostError = ChatApiChatPostErrors[keyof ChatApiChatPostErrors];

export type ChatApiChatPostResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ChatApiChatPostResponse = ChatApiChatPostResponses[keyof ChatApiChatPostResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckApiHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthCheckApiHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: `${string}://apps` | (string & {});
};